import type { User, DevelopmentData, TimetableDocument, TimetableEntry, Holiday, SubjectReference, TeacherLeave, Course, AcademicClass } from '../../types/domain'

export const developmentUsers: User[] = [
  {
    id: 'student-1',
    role: 'student',
    name: 'Aarav Sharma',
    email: 'aarav@edupulse.dev',
    avatar: 'AS',
    college: 'Bonsalo College',
    identifier: 'BIT-24-041',
    phone: '+91 98765 43210',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicClassId: 'class-bscit-s2-a-2026',
    batch: '2024–2027',
    department: 'Information Technology',
    status: 'active',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'student-2',
    role: 'student',
    name: 'Rahul Verma',
    email: 'rahul@edupulse.dev',
    avatar: 'RV',
    college: 'Bonsalo College',
    identifier: 'BCOM-24-012',
    phone: '+91 98765 43211',
    course: 'Bachelor of Commerce',
    semester: '2',
    division: 'A',
    academicClassId: 'class-bcom-s2-a-2026',
    batch: '2024–2027',
    department: 'Commerce',
    status: 'active',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'student-3',
    role: 'student',
    name: 'Sneha Patil',
    email: 'sneha@edupulse.dev',
    avatar: 'SP',
    college: 'Bonsalo College',
    identifier: 'BDS-24-089',
    phone: '+91 98765 43212',
    course: 'BSc Data Science',
    semester: '2',
    division: 'A',
    academicClassId: 'class-bscds-s2-a-2026',
    batch: '2024–2027',
    department: 'Data Science',
    status: 'active',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'teacher-1',
    role: 'teacher',
    name: 'Dr. Meera Shah',
    email: 'meera@edupulse.dev',
    avatar: 'MS',
    college: 'Bonsalo College',
    identifier: 'EMP-1027',
    phone: '+91 98234 56789',
    department: 'Computer Science',
    designation: 'Associate Professor',
    subjects: ['Data Structures', 'Web Development', 'Algorithms'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2022-06-15T00:00:00.000Z',
  },
  {
    id: 'teacher-2',
    role: 'teacher',
    name: 'Prof. Rohan Mehta',
    email: 'rohan@edupulse.dev',
    avatar: 'RM',
    college: 'Bonsalo College',
    identifier: 'EMP-1028',
    phone: '+91 98234 56790',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    subjects: ['Operating Systems', 'Java Programming', 'Computer Networks'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2023-01-10T00:00:00.000Z',
  },
  {
    id: 'teacher-3',
    role: 'teacher',
    name: 'Prof. Rahul Sharma',
    email: 'rahul.sharma@edupulse.dev',
    avatar: 'RS',
    college: 'Bonsalo College',
    identifier: 'EMP-1029',
    phone: '+91 98234 56791',
    department: 'Information Technology',
    designation: 'Associate Professor',
    subjects: ['Artificial Intelligence', 'Python Programming', 'Machine Learning', 'Business Statistics'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2023-06-01T00:00:00.000Z',
  },
  {
    id: 'teacher-4',
    role: 'teacher',
    name: 'Dr. Anjali Sharma',
    email: 'anjali@edupulse.dev',
    avatar: 'AS',
    college: 'Bonsalo College',
    identifier: 'EMP-1030',
    phone: '+91 98234 56792',
    department: 'Computer Science',
    designation: 'Professor',
    subjects: ['Cloud Computing', 'Artificial Intelligence', 'Network Security'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2021-08-15T00:00:00.000Z',
  },
  {
    id: 'teacher-5',
    role: 'teacher',
    name: 'Prof. Priya Shah',
    email: 'priya.shah@edupulse.dev',
    avatar: 'PS',
    college: 'Bonsalo College',
    identifier: 'EMP-1031',
    phone: '+91 98234 56793',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    subjects: ['Artificial Intelligence', 'Data Structures'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'teacher-6',
    role: 'teacher',
    name: 'Prof. Amit Patil',
    email: 'amit.patil@edupulse.dev',
    avatar: 'AP',
    college: 'Bonsalo College',
    identifier: 'EMP-1032',
    phone: '+91 98234 56794',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    subjects: ['Artificial Intelligence', 'Cloud Computing'],
    verificationStatus: 'approved',
    status: 'active',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'admin-1',
    role: 'admin',
    name: 'Priya Nair',
    email: 'principal@edupulse.dev',
    avatar: 'PN',
    college: 'Bonsalo College',
    identifier: 'ADMIN-001',
    phone: '+91 98111 22334',
    department: 'Administration',
    designation: 'Principal',
    status: 'active',
    createdAt: '2020-01-10T00:00:00.000Z',
  },
]

export const initialCourses: Course[] = [
  {
    id: 'course-bit',
    collegeId: 'Bonsalo College',
    name: 'BSc IT',
    code: 'BIT',
    department: 'Information Technology',
    durationYears: 3,
    totalSemesters: 6,
    years: ['FY', 'SY', 'TY'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'course-bds',
    collegeId: 'Bonsalo College',
    name: 'BSc Data Science',
    code: 'BDS',
    department: 'Data Science',
    durationYears: 3,
    totalSemesters: 6,
    years: ['FY', 'SY', 'TY'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'course-bcom',
    collegeId: 'Bonsalo College',
    name: 'Bachelor of Commerce',
    code: 'BCOM',
    department: 'Commerce',
    durationYears: 3,
    totalSemesters: 6,
    years: ['FY', 'SY', 'TY'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'course-bca',
    collegeId: 'Bonsalo College',
    name: 'Bachelor of Computer Applications (BCA)',
    code: 'BCA',
    department: 'Computer Applications',
    durationYears: 3,
    totalSemesters: 6,
    years: ['FY', 'SY', 'TY'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'course-bcs',
    collegeId: 'Bonsalo College',
    name: 'BSc Computer Science',
    code: 'BCS',
    department: 'Computer Science',
    durationYears: 3,
    totalSemesters: 6,
    years: ['FY', 'SY', 'TY'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
]

export const initialAcademicClasses: AcademicClass[] = [
  {
    id: 'class-bscit-s2-a-2026',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'FY',
    semester: '2',
    division: 'A',
    name: 'BSc IT - Sem 2 - Div A',
    displayName: 'BSc IT - Sem 2 - Div A',
    academicYear: '2026-27',
    teacherIds: ['teacher-1', 'teacher-2', 'teacher-3'],
    studentIds: ['student-1'],
    isActive: true,
    status: 'active',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-bscit-s2-b-2026',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'FY',
    semester: '2',
    division: 'B',
    name: 'BSc IT - Sem 2 - Div B',
    displayName: 'BSc IT - Sem 2 - Div B',
    academicYear: '2026-27',
    teacherIds: ['teacher-2', 'teacher-5'],
    studentIds: [],
    isActive: true,
    status: 'active',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-bscds-s2-a-2026',
    collegeId: 'Bonsalo College',
    courseId: 'course-bds',
    courseName: 'BSc Data Science',
    year: 'FY',
    semester: '2',
    division: 'A',
    name: 'BSc DS - Sem 2 - Div A',
    displayName: 'BSc Data Science - Sem 2 - Div A',
    academicYear: '2026-27',
    teacherIds: ['teacher-1', 'teacher-6'],
    studentIds: ['student-3'],
    isActive: true,
    status: 'active',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-bcom-s2-a-2026',
    collegeId: 'Bonsalo College',
    courseId: 'course-bcom',
    courseName: 'Bachelor of Commerce',
    year: 'FY',
    semester: '2',
    division: 'A',
    name: 'BCom - Sem 2 - Div A',
    displayName: 'Bachelor of Commerce - Sem 2 - Div A',
    academicYear: '2026-27',
    teacherIds: ['teacher-1', 'teacher-3'],
    studentIds: ['student-2'],
    isActive: true,
    status: 'active',
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-tyit-a',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'TY',
    semester: '5',
    division: 'A',
    name: 'TYIT-A',
    academicYear: '2026-27',
    teacherIds: ['teacher-3', 'teacher-1', 'teacher-2'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-tyit-b',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'TY',
    semester: '5',
    division: 'B',
    name: 'TYIT-B',
    academicYear: '2026-27',
    teacherIds: ['teacher-5', 'teacher-2'],
    studentIds: ['student-2'],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-tyit-c',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'TY',
    semester: '5',
    division: 'C',
    name: 'TYIT-C',
    academicYear: '2026-27',
    teacherIds: ['teacher-6', 'teacher-3'],
    studentIds: ['student-3'],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-syit-a',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'SY',
    semester: '3',
    division: 'A',
    name: 'SYIT-A',
    academicYear: '2026-27',
    teacherIds: ['teacher-1', 'teacher-2'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-fyit-a',
    collegeId: 'Bonsalo College',
    courseId: 'course-bit',
    courseName: 'BSc IT',
    year: 'FY',
    semester: '1',
    division: 'A',
    name: 'FYIT-A',
    academicYear: '2026-27',
    teacherIds: ['teacher-2', 'teacher-4'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-syds-b',
    collegeId: 'Bonsalo College',
    courseId: 'course-bds',
    courseName: 'BSc Data Science',
    year: 'SY',
    semester: '3',
    division: 'B',
    name: 'SYDS-B',
    academicYear: '2026-27',
    teacherIds: ['teacher-3'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-bcom-a',
    collegeId: 'Bonsalo College',
    courseId: 'course-bcom',
    courseName: 'Bachelor of Commerce',
    year: 'TY',
    semester: '5',
    division: 'A',
    name: 'BCom-A',
    academicYear: '2026-27',
    teacherIds: ['teacher-3'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'class-tycs-a',
    collegeId: 'Bonsalo College',
    courseId: 'course-bcs',
    courseName: 'BSc Computer Science',
    year: 'TY',
    semester: '5',
    division: 'A',
    name: 'TYCS-A',
    academicYear: '2026-27',
    teacherIds: ['teacher-1', 'teacher-4'],
    studentIds: [],
    isActive: true,
    createdAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
]

export const initialSubjects: SubjectReference[] = [
  { id: 'sub-1', collegeId: 'Bonsalo College', name: 'Data Structures', code: 'IT201', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-2', collegeId: 'Bonsalo College', name: 'Operating Systems', code: 'IT202', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-3', collegeId: 'Bonsalo College', name: 'Java Programming', code: 'IT203', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-4', collegeId: 'Bonsalo College', name: 'Web Development', code: 'IT204', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-5', collegeId: 'Bonsalo College', name: 'Database Management Systems', code: 'IT205', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-6', collegeId: 'Bonsalo College', name: 'Computer Networks', code: 'IT206', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-ai-s2', collegeId: 'Bonsalo College', name: 'Artificial Intelligence', code: 'IT207', course: 'BSc IT', semester: '2', department: 'Information Technology' },
  { id: 'sub-bds-ds', collegeId: 'Bonsalo College', name: 'Data Structures', code: 'DS201', course: 'BSc Data Science', semester: '2', department: 'Data Science' },
  { id: 'sub-bds-dbms', collegeId: 'Bonsalo College', name: 'Database Management', code: 'DS202', course: 'BSc Data Science', semester: '2', department: 'Data Science' },
  { id: 'sub-bds-py', collegeId: 'Bonsalo College', name: 'Python Programming', code: 'DS203', course: 'BSc Data Science', semester: '2', department: 'Data Science' },
  { id: 'sub-bcom-biz', collegeId: 'Bonsalo College', name: 'Business Applications', code: 'COM201', course: 'Bachelor of Commerce', semester: '2', department: 'Commerce' },
  { id: 'sub-bcom-stats', collegeId: 'Bonsalo College', name: 'Business Statistics', code: 'COM202', course: 'Bachelor of Commerce', semester: '2', department: 'Commerce' },
  { id: 'sub-ai', collegeId: 'Bonsalo College', name: 'Artificial Intelligence', code: 'IT501', course: 'BSc IT', semester: '5', department: 'Information Technology' },
  { id: 'sub-py', collegeId: 'Bonsalo College', name: 'Python Programming', code: 'DS301', course: 'BSc Data Science', semester: '3', department: 'Data Science' },
  { id: 'sub-stats', collegeId: 'Bonsalo College', name: 'Business Statistics', code: 'COM501', course: 'Bachelor of Commerce', semester: '5', department: 'Commerce' },
  { id: 'sub-cc', collegeId: 'Bonsalo College', name: 'Cloud Computing', code: 'IT502', course: 'BSc IT', semester: '5', department: 'Information Technology' },
  { id: 'sub-sec', collegeId: 'Bonsalo College', name: 'Cyber Security', code: 'IT503', course: 'BSc IT', semester: '5', department: 'Information Technology' },
]

export const initialHolidays: Holiday[] = [
  {
    id: 'hol-1',
    collegeId: 'Bonsalo College',
    name: 'Ganesh Chaturthi',
    date: '2026-09-19',
    scope: 'all',
    description: 'Campus holiday on account of Ganesh Chaturthi celebrations.',
    createdBy: 'Priya Nair',
    createdAt: '2026-08-15T00:00:00.000Z',
  },
  {
    id: 'hol-2',
    collegeId: 'Bonsalo College',
    name: 'Gandhi Jayanti',
    date: '2026-10-02',
    scope: 'all',
    description: 'National holiday in commemoration of Mahatma Gandhi Jayanti.',
    createdBy: 'Priya Nair',
    createdAt: '2026-08-15T00:00:00.000Z',
  },
]

export const initialTeacherLeaves: TeacherLeave[] = [
  {
    id: 'leave-1',
    collegeId: 'Bonsalo College',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    teacherEmail: 'meera@edupulse.dev',
    teacherDepartment: 'Computer Science',
    startDate: '2026-09-25',
    endDate: '2026-09-27',
    leaveType: 'Full Day',
    reason: 'Attending National Conference on Data Engineering & Algorithms',
    status: 'UPCOMING',
    affectedLectureCount: 3,
    cancelledCount: 0,
    substitutedCount: 0,
    rescheduledCount: 0,
    createdBy: 'admin-1',
    createdByName: 'Dr. Sanjay Deshmukh',
    createdByRole: 'admin',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'leave-2',
    collegeId: 'Bonsalo College',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Sharma',
    teacherEmail: 'rahul.sharma@edupulse.dev',
    teacherDepartment: 'Information Technology',
    startDate: '2026-10-02',
    endDate: '2026-10-03',
    leaveType: 'Full Day',
    reason: 'Faculty Development Program on Cloud Native Architectures',
    status: 'UPCOMING',
    affectedLectureCount: 2,
    cancelledCount: 0,
    substitutedCount: 0,
    rescheduledCount: 0,
    createdBy: 'admin-1',
    createdByName: 'Dr. Sanjay Deshmukh',
    createdByRole: 'admin',
    createdAt: '2026-09-02T11:00:00.000Z',
    updatedAt: '2026-09-02T11:00:00.000Z',
  },
  {
    id: 'leave-3',
    collegeId: 'Bonsalo College',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    teacherEmail: 'rohan@edupulse.dev',
    teacherDepartment: 'Information Technology',
    startDate: '2026-08-10',
    endDate: '2026-08-12',
    leaveType: 'Full Day',
    reason: 'Medical Leave - Viral Fever recovery',
    status: 'COMPLETED',
    actualReturnDate: '2026-08-13',
    returnNotes: 'Returned to campus duty in full health.',
    affectedLectureCount: 2,
    cancelledCount: 1,
    substitutedCount: 1,
    rescheduledCount: 0,
    createdBy: 'admin-1',
    createdByName: 'Dr. Sanjay Deshmukh',
    createdByRole: 'admin',
    createdAt: '2026-08-08T09:00:00.000Z',
    updatedAt: '2026-08-13T09:00:00.000Z',
  },
]


export const initialTimetableDocuments: TimetableDocument[] = [
  {
    id: 'tt-doc-1',
    collegeId: 'Bonsalo College',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    fileUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1600&q=80',
    fileName: 'BSc_IT_Sem2_DivA_Official_Timetable.png',
    fileType: 'image',
    fileSize: 485200,
    version: 1,
    effectiveFrom: '2026-08-01',
    uploadedBy: 'Priya Nair',
    uploadedAt: '2026-08-01T09:00:00.000Z',
    isActive: true,
    status: 'published',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
  },
]

export const initialTimetableEntries: TimetableEntry[] = [
  // --- Multi-Course & Multi-Class Schedules (TYIT-A, TYIT-B, TYIT-C, SYDS-B, BCom-A) ---
  {
    id: 'tt-rs-1',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-a',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '07:30',
    endTime: '08:30',
    time: '07:30 – 08:30',
    subjectId: 'sub-ai',
    subjectName: 'Artificial Intelligence',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Sharma',
    room: 'Lab 1',
    type: 'Lab',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T07:30:00.000Z',
    updatedAt: '2026-08-01T07:30:00.000Z',
    day: 'Monday',
    subject: 'Artificial Intelligence',
    teacher: 'Prof. Rahul Sharma',
    className: 'TYIT-A',
  },
  {
    id: 'tt-para-b',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-b',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'B',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '07:30',
    endTime: '08:30',
    time: '07:30 – 08:30',
    subjectId: 'sub-ai',
    subjectName: 'Artificial Intelligence',
    teacherId: 'teacher-5',
    teacherName: 'Prof. Priya Shah',
    room: 'Lab 2',
    type: 'Lab',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T07:30:00.000Z',
    updatedAt: '2026-08-01T07:30:00.000Z',
    day: 'Monday',
    subject: 'Artificial Intelligence',
    teacher: 'Prof. Priya Shah',
    className: 'TYIT-B',
  },
  {
    id: 'tt-para-c',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-c',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'C',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '07:30',
    endTime: '08:30',
    time: '07:30 – 08:30',
    subjectId: 'sub-ai',
    subjectName: 'Artificial Intelligence',
    teacherId: 'teacher-6',
    teacherName: 'Prof. Amit Patil',
    room: 'Lab 3',
    type: 'Lab',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T07:30:00.000Z',
    updatedAt: '2026-08-01T07:30:00.000Z',
    day: 'Monday',
    subject: 'Artificial Intelligence',
    teacher: 'Prof. Amit Patil',
    className: 'TYIT-C',
  },
  {
    id: 'tt-rs-2',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bds',
    classId: 'class-syds-b',
    year: 'SY',
    course: 'BSc Data Science',
    semester: '3',
    division: 'B',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '08:30',
    endTime: '09:30',
    time: '08:30 – 09:30',
    subjectId: 'sub-py',
    subjectName: 'Python Programming',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Sharma',
    room: 'Lab 4',
    type: 'Lab',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T08:30:00.000Z',
    updatedAt: '2026-08-01T08:30:00.000Z',
    day: 'Monday',
    subject: 'Python Programming',
    teacher: 'Prof. Rahul Sharma',
    className: 'SYDS-B',
  },
  {
    id: 'tt-rs-3',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bcom',
    classId: 'class-bcom-a',
    year: 'TY',
    course: 'Bachelor of Commerce',
    semester: '5',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '09:50',
    endTime: '10:50',
    time: '09:50 – 10:50',
    subjectId: 'sub-stats',
    subjectName: 'Business Statistics',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Sharma',
    room: 'Room 204',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:50:00.000Z',
    updatedAt: '2026-08-01T09:50:00.000Z',
    day: 'Monday',
    subject: 'Business Statistics',
    teacher: 'Prof. Rahul Sharma',
    className: 'BCom-A',
  },
  {
    id: 'tt-rs-4',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-c',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'C',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '11:00',
    endTime: '12:00',
    time: '11:00 – 12:00',
    subjectId: 'sub-ai',
    subjectName: 'Artificial Intelligence',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Sharma',
    room: 'Lab 2',
    type: 'Lab',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T11:00:00.000Z',
    updatedAt: '2026-08-01T11:00:00.000Z',
    day: 'Monday',
    subject: 'Artificial Intelligence',
    teacher: 'Prof. Rahul Sharma',
    className: 'TYIT-C',
  },
  {
    id: 'tt-tyit-a-tue',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-a',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Tuesday',
    startTime: '08:30',
    endTime: '09:30',
    time: '08:30 – 09:30',
    subjectId: 'sub-cc',
    subjectName: 'Cloud Computing',
    teacherId: 'teacher-4',
    teacherName: 'Dr. Anjali Sharma',
    room: 'Room 304',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T08:30:00.000Z',
    updatedAt: '2026-08-01T08:30:00.000Z',
    day: 'Tuesday',
    subject: 'Cloud Computing',
    teacher: 'Dr. Anjali Sharma',
    className: 'TYIT-A',
  },
  {
    id: 'tt-tyit-a-wed',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-tyit-a',
    year: 'TY',
    course: 'BSc IT',
    semester: '5',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Wednesday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-sec',
    subjectName: 'Cyber Security',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: 'Room 302',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Wednesday',
    subject: 'Cyber Security',
    teacher: 'Prof. Rohan Mehta',
    className: 'TYIT-A',
  },
  {
    id: 'tt-1',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-a-2026',
    academicClassId: 'class-bscit-s2-a-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-1',
    subjectName: 'Data Structures',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Room 304',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Data Structures',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT - Sem 2 - Div A',
  },
  {
    id: 'tt-meera-bds-tue',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bds',
    classId: 'class-bscds-s2-a-2026',
    academicClassId: 'class-bscds-s2-a-2026',
    course: 'BSc Data Science',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Tuesday',
    startTime: '10:00',
    endTime: '11:00',
    time: '10:00 – 11:00',
    subjectId: 'sub-bds-ds',
    subjectName: 'Data Structures',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Lab 1',
    type: 'Practical',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
    day: 'Tuesday',
    subject: 'Data Structures',
    teacher: 'Dr. Meera Shah',
    className: 'BSc DS - Sem 2 - Div A',
  },
  {
    id: 'tt-meera-bcom-wed',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bcom',
    classId: 'class-bcom-s2-a-2026',
    academicClassId: 'class-bcom-s2-a-2026',
    course: 'Bachelor of Commerce',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Wednesday',
    startTime: '11:00',
    endTime: '12:00',
    time: '11:00 – 12:00',
    subjectId: 'sub-bcom-biz',
    subjectName: 'Business Applications',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Room 201',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T11:00:00.000Z',
    updatedAt: '2026-08-01T11:00:00.000Z',
    day: 'Wednesday',
    subject: 'Business Applications',
    teacher: 'Dr. Meera Shah',
    className: 'BCom - Sem 2 - Div A',
  },
  {
    id: 'tt-rohan-bscit-b-mon',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-b-2026',
    academicClassId: 'class-bscit-s2-b-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'B',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '10:00',
    endTime: '11:00',
    time: '10:00 – 11:00',
    subjectId: 'sub-3',
    subjectName: 'Java Programming',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: 'Lab 1',
    type: 'Practical',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
    day: 'Monday',
    subject: 'Java Programming',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT - Sem 2 - Div B',
  },
  {
    id: 'tt-amit-bscds-a-mon',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bds',
    classId: 'class-bscds-s2-a-2026',
    academicClassId: 'class-bscds-s2-a-2026',
    course: 'BSc Data Science',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-bds-dbms',
    subjectName: 'Database Management',
    teacherId: 'teacher-6',
    teacherName: 'Prof. Amit Patil',
    room: 'Room 205',
    type: 'Regular',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Database Management',
    teacher: 'Prof. Amit Patil',
    className: 'BSc DS - Sem 2 - Div A',
  },
  {
    id: 'tt-2',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-a-2026',
    academicClassId: 'class-bscit-s2-a-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-2',
    subjectName: 'Operating Systems',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: '205',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Operating Systems',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT - Sem 2 - Div A',
  },
  {
    id: 'tt-3',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-a-2026',
    academicClassId: 'class-bscit-s2-a-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '11:30',
    endTime: '12:30',
    time: '11:30 – 12:30',
    subjectId: 'sub-4',
    subjectName: 'Web Development',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Lab 2',
    status: 'Cancelled',
    entryType: 'weekly',
    reason: 'Faculty attending syllabus revision committee',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Web Development',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT - Sem 2 - Div A',
  },
  {
    id: 'tt-4',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-a-2026',
    academicClassId: 'class-bscit-s2-a-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Tuesday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-3',
    subjectName: 'Java Programming',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: '304',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Tuesday',
    subject: 'Java Programming',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT - Sem 2 - Div A',
  },
  {
    id: 'tt-5',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    courseId: 'course-bit',
    classId: 'class-bscit-s2-a-2026',
    academicClassId: 'class-bscit-s2-a-2026',
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Tuesday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-5',
    subjectName: 'Database Management Systems',
    teacherId: 'teacher-4',
    teacherName: 'Dr. Anjali Sharma',
    room: '203',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Tuesday',
    subject: 'Database Management Systems',
    teacher: 'Dr. Anjali Sharma',
    className: 'BSc IT - Sem 2 - Div A',
  },
  {
    id: 'tt-6',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Wednesday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-4',
    subjectName: 'Web Development',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Lab 2',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Wednesday',
    subject: 'Web Development',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-7',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Wednesday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-1',
    subjectName: 'Data Structures',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: '304',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Wednesday',
    subject: 'Data Structures',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-8',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Thursday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-3',
    subjectName: 'Java Programming',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: '304',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Thursday',
    subject: 'Java Programming',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-9',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Thursday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-2',
    subjectName: 'Operating Systems',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: '205',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Thursday',
    subject: 'Operating Systems',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-10',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Friday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-6',
    subjectName: 'Computer Networks',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Rohan Mehta',
    room: '205',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Friday',
    subject: 'Computer Networks',
    teacher: 'Prof. Rohan Mehta',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-11',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Friday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-5',
    subjectName: 'Database Management Systems',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: '203',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Friday',
    subject: 'Database Management Systems',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-12',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '2',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Saturday',
    startTime: '09:00',
    endTime: '10:30',
    time: '09:00 – 10:30',
    subjectId: 'sub-1',
    subjectName: 'Data Structures Lab',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Meera Shah',
    room: 'Lab 1',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Saturday',
    subject: 'Data Structures Lab',
    teacher: 'Dr. Meera Shah',
    className: 'BSc IT · Sem 2 · A',
  },
  {
    id: 'tt-13',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '3',
    division: 'B',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-5',
    subjectName: 'Database Systems',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Patil',
    room: '203',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Database Systems',
    teacher: 'Prof. Rahul Patil',
    className: 'BSc IT · Sem 3 · B',
  },
  {
    id: 'tt-14',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc Computer Science',
    semester: '4',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Monday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-cs-1',
    subjectName: 'Cloud Computing',
    teacherId: 'teacher-4',
    teacherName: 'Dr. Anjali Sharma',
    room: '101',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Monday',
    subject: 'Cloud Computing',
    teacher: 'Dr. Anjali Sharma',
    className: 'BSc CS · Sem 4 · A',
  },
  {
    id: 'tt-15',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '1',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Tuesday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-it-1',
    subjectName: 'Discrete Mathematics',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Patil',
    room: '301',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Tuesday',
    subject: 'Discrete Mathematics',
    teacher: 'Prof. Rahul Patil',
    className: 'BSc IT · Sem 1 · A',
  },
  {
    id: 'tt-16',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc Computer Science',
    semester: '6',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Wednesday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-cs-2',
    subjectName: 'Artificial Intelligence',
    teacherId: 'teacher-4',
    teacherName: 'Dr. Anjali Sharma',
    room: '203',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Wednesday',
    subject: 'Artificial Intelligence',
    teacher: 'Dr. Anjali Sharma',
    className: 'BSc CS · Sem 6 · A',
  },
  {
    id: 'tt-17',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc IT',
    semester: '4',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Thursday',
    startTime: '10:15',
    endTime: '11:15',
    time: '10:15 – 11:15',
    subjectId: 'sub-it-2',
    subjectName: 'Mobile App Development',
    teacherId: 'teacher-3',
    teacherName: 'Prof. Rahul Patil',
    room: 'Lab 101',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Thursday',
    subject: 'Mobile App Development',
    teacher: 'Prof. Rahul Patil',
    className: 'BSc IT · Sem 4 · A',
  },
  {
    id: 'tt-18',
    collegeId: 'Bonsalo College',
    timetableDocumentId: 'tt-doc-1',
    version: 1,
    course: 'BSc Computer Science',
    semester: '6',
    division: 'A',
    academicYear: '2026-27',
    dayOfWeek: 'Friday',
    startTime: '09:00',
    endTime: '10:00',
    time: '09:00 – 10:00',
    subjectId: 'sub-cs-3',
    subjectName: 'Network Security',
    teacherId: 'teacher-4',
    teacherName: 'Dr. Anjali Sharma',
    room: '202',
    status: 'Scheduled',
    entryType: 'weekly',
    createdBy: 'admin-1',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
    day: 'Friday',
    subject: 'Network Security',
    teacher: 'Dr. Anjali Sharma',
    className: 'BSc CS · Sem 6 · A',
  },
]

export const initialData: DevelopmentData = {
  users: developmentUsers,
  courses: initialCourses,
  classes: initialAcademicClasses,
  timetable: initialTimetableEntries as any,
  timetableDocuments: initialTimetableDocuments,
  timetableEntries: initialTimetableEntries,
  holidays: initialHolidays,
  teacherLeaves: initialTeacherLeaves,
  subjects: initialSubjects,
  announcements: [
    { id: 'ann-1', title: 'Mid-semester assessment schedule', description: 'The assessment timetable has been published. Please review your subject slots and report conflicts by Friday.', postedBy: 'Academic Office', date: 'Today, 09:30 AM', category: 'Academic', readBy: [] },
    { id: 'ann-2', title: 'CodeQuest registrations are open', description: 'Register your team for the annual inter-college programming challenge before 18 September.', postedBy: 'Dr. Meera Shah', date: 'Yesterday', category: 'Event', readBy: ['student-1'] },
    { id: 'ann-3', title: 'Library hours extended', description: 'The central library will remain open until 8 PM during the examination preparation period.', postedBy: 'Principal Office', date: '30 Aug 2026', category: 'General', readBy: [] },
  ],
  materials: [
    { id: 'mat-1', title: 'Binary Search Notes', subject: 'Data Structures', teacher: 'Dr. Meera Shah', className: 'BSc IT · Sem 2 · A', fileType: 'PDF', date: 'Today', description: 'Worked examples, recursive and iterative implementations.' },
    { id: 'mat-2', title: 'Process Scheduling Slides', subject: 'Operating Systems', teacher: 'Prof. Rohan Mehta', className: 'BSc IT · Sem 2 · A', fileType: 'PPTX', date: 'Yesterday', description: 'CPU scheduling algorithms and comparisons.' },
    { id: 'mat-3', title: 'Responsive Layout Lab', subject: 'Web Development', teacher: 'Dr. Meera Shah', className: 'BSc IT · Sem 2 · A', fileType: 'DOCX', date: '29 Aug 2026', description: 'Practical exercise for mobile-first CSS.' },
  ],
  assignments: [
    { id: 'as-1', title: 'Implement a Binary Search Tree', description: 'Create a TypeScript implementation of a binary search tree with insert, search, and traversal methods. Include a short README describing your approach.', subject: 'Data Structures', teacher: 'Dr. Meera Shah', className: 'BSc IT · Sem 2 · A', dueDate: '12 Sep 2026', status: 'Pending' },
    { id: 'as-2', title: 'Process Scheduling Comparison', description: 'Compare FCFS, SJF, and Round Robin scheduling for the supplied process set.', subject: 'Operating Systems', teacher: 'Prof. Rohan Mehta', className: 'BSc IT · Sem 2 · A', dueDate: '06 Sep 2026', status: 'Submitted', submissionFileName: 'scheduling-comparison.pdf' },
    { id: 'as-3', title: 'Portfolio Landing Page', description: 'Build a responsive personal portfolio landing page using semantic HTML and CSS.', subject: 'Web Development', teacher: 'Dr. Meera Shah', className: 'BSc IT · Sem 2 · A', dueDate: '28 Aug 2026', status: 'Graded', marks: '18 / 20', feedback: 'Excellent information hierarchy and responsiveness.' },
  ],
  doubts: [
    { id: 'doubt-1', subject: 'Data Structures', question: 'Why is binary search O(log n) instead of O(n)?', studentName: 'Aarav Sharma', date: 'Today, 08:10 AM', status: 'Answered', response: 'Each comparison discards half of the remaining ordered values, so the number of steps grows logarithmically.', teacherName: 'Dr. Meera Shah' },
    { id: 'doubt-2', subject: 'Operating Systems', question: 'Can pre-emptive SJF cause starvation?', studentName: 'Ishita Patel', date: 'Yesterday', status: 'Pending' },
  ],
  messages: [
    { id: 'msg-1', senderName: 'Dr. Meera Shah', senderRole: 'teacher', text: 'The Web Development lab is cancelled today. Please use the slot to complete the responsive layout exercise.', date: '09:05 AM' },
    { id: 'msg-2', senderName: 'Aarav Sharma', senderRole: 'student', text: 'Will the binary tree assignment need unit tests as well?', date: '09:12 AM' },
    { id: 'msg-3', senderName: 'Dr. Meera Shah', senderRole: 'teacher', text: 'Yes — cover insert, search, and each traversal in your tests.', date: '09:16 AM' },
  ],
  conversations: [
    {
      id: 'conv-group-1',
      type: 'group',
      category: 'class',
      collegeId: 'Bonsalo College',
      name: 'BSc IT · Sem 2 · A',
      description: 'Official academic class communication group for Semester 2 Section A students and faculty.',
      avatar: 'IT',
      participants: ['student-1', 'student-2', 'student-3', 'teacher-1', 'teacher-2'],
      participantDetails: {
        'student-1': { id: 'student-1', name: 'Aarav Sharma', role: 'student', avatar: 'AS', identifier: 'BIT-24-041', department: 'BSc IT' },
        'student-2': { id: 'student-2', name: 'Rahul Verma', role: 'student', avatar: 'RV', identifier: 'BIT-24-042', department: 'BSc IT' },
        'student-3': { id: 'student-3', name: 'Sneha Patil', role: 'student', avatar: 'SP', identifier: 'BIT-24-043', department: 'BSc IT' },
        'teacher-1': { id: 'teacher-1', name: 'Dr. Meera Shah', role: 'teacher', avatar: 'MS', identifier: 'EMP-1027', department: 'Computer Science' },
        'teacher-2': { id: 'teacher-2', name: 'Prof. Rohan Mehta', role: 'teacher', avatar: 'RM', identifier: 'EMP-1028', department: 'Information Technology' },
      },
      adminIds: ['teacher-1', 'teacher-2'],
      lastMessage: 'Yes — cover insert, search, and each traversal in your tests.',
      lastMessageAt: '09:16 AM',
      lastMessageSender: 'Dr. Meera Shah',
      unreadCount: { 'student-1': 0, 'teacher-1': 0 },
      isMuted: {},
      createdAt: '2026-08-20T08:00:00.000Z',
      updatedAt: '2026-09-05T09:16:00.000Z',
      createdBy: 'teacher-1',
    },
    {
      id: 'conv-personal-1',
      type: 'personal',
      collegeId: 'Bonsalo College',
      participants: ['student-1', 'teacher-1'],
      participantDetails: {
        'student-1': { id: 'student-1', name: 'Aarav Sharma', role: 'student', avatar: 'AS', identifier: 'BIT-24-041', department: 'BSc IT' },
        'teacher-1': { id: 'teacher-1', name: 'Dr. Meera Shah', role: 'teacher', avatar: 'MS', identifier: 'EMP-1027', department: 'Computer Science' },
      },
      lastMessage: 'Good afternoon ma\'am, I had a doubt regarding the binary tree assignment deadline.',
      lastMessageAt: 'Yesterday',
      lastMessageSender: 'Aarav Sharma',
      unreadCount: { 'teacher-1': 1, 'student-1': 0 },
      isMuted: {},
      createdAt: '2026-08-25T10:00:00.000Z',
      updatedAt: '2026-09-04T16:20:00.000Z',
      createdBy: 'student-1',
    },
    {
      id: 'conv-group-2',
      type: 'group',
      category: 'custom',
      collegeId: 'Bonsalo College',
      name: 'Project Team Alpha',
      description: 'Student coordination group for the web development capstone project.',
      avatar: 'PA',
      participants: ['student-1', 'student-2', 'student-3'],
      participantDetails: {
        'student-1': { id: 'student-1', name: 'Aarav Sharma', role: 'student', avatar: 'AS', identifier: 'BIT-24-041', department: 'BSc IT' },
        'student-2': { id: 'student-2', name: 'Rahul Verma', role: 'student', avatar: 'RV', identifier: 'BIT-24-042', department: 'BSc IT' },
        'student-3': { id: 'student-3', name: 'Sneha Patil', role: 'student', avatar: 'SP', identifier: 'BIT-24-043', department: 'BSc IT' },
      },
      adminIds: ['student-1'],
      lastMessage: 'I have pushed the navbar changes to GitHub.',
      lastMessageAt: 'Yesterday',
      lastMessageSender: 'Rahul Verma',
      unreadCount: { 'student-1': 0 },
      isMuted: {},
      createdAt: '2026-08-28T14:00:00.000Z',
      updatedAt: '2026-09-04T18:45:00.000Z',
      createdBy: 'student-1',
    },
  ],
  chatMessages: [
    {
      id: 'cmsg-1',
      conversationId: 'conv-group-1',
      collegeId: 'Bonsalo College',
      senderId: 'teacher-1',
      senderName: 'Dr. Meera Shah',
      senderRole: 'teacher',
      senderAvatar: 'MS',
      text: 'The Web Development lab is cancelled today. Please use the slot to complete the responsive layout exercise.',
      status: 'read',
      createdAt: '09:05 AM',
    },
    {
      id: 'cmsg-2',
      conversationId: 'conv-group-1',
      collegeId: 'Bonsalo College',
      senderId: 'student-1',
      senderName: 'Aarav Sharma',
      senderRole: 'student',
      senderAvatar: 'AS',
      text: 'Will the binary tree assignment need unit tests as well?',
      status: 'read',
      createdAt: '09:12 AM',
    },
    {
      id: 'cmsg-3',
      conversationId: 'conv-group-1',
      collegeId: 'Bonsalo College',
      senderId: 'teacher-1',
      senderName: 'Dr. Meera Shah',
      senderRole: 'teacher',
      senderAvatar: 'MS',
      text: 'Yes — cover insert, search, and each traversal in your tests.',
      replyTo: {
        id: 'cmsg-2',
        senderName: 'Aarav Sharma',
        text: 'Will the binary tree assignment need unit tests as well?',
      },
      status: 'read',
      createdAt: '09:16 AM',
    },
    {
      id: 'cmsg-4',
      conversationId: 'conv-personal-1',
      collegeId: 'Bonsalo College',
      senderId: 'student-1',
      senderName: 'Aarav Sharma',
      senderRole: 'student',
      senderAvatar: 'AS',
      text: 'Good afternoon ma\'am, I had a doubt regarding the binary tree assignment deadline.',
      status: 'delivered',
      createdAt: 'Yesterday, 04:20 PM',
    },
    {
      id: 'cmsg-5',
      conversationId: 'conv-group-2',
      collegeId: 'Bonsalo College',
      senderId: 'student-2',
      senderName: 'Rahul Verma',
      senderRole: 'student',
      senderAvatar: 'RV',
      text: 'I have pushed the navbar changes to GitHub.',
      status: 'read',
      createdAt: 'Yesterday, 06:45 PM',
    },
    {
      id: 'cmsg-6',
      conversationId: 'conv-faculty-lounge',
      collegeId: 'Bonsalo College',
      senderId: 'admin-1',
      senderName: 'Priya Nair',
      senderRole: 'admin',
      senderAvatar: 'PN',
      text: 'Welcome colleagues to the Faculty & Admin Board. Please ensure mid-semester internal marks are submitted by Friday.',
      status: 'read',
      createdAt: 'Yesterday, 10:15 AM',
    },
    {
      id: 'cmsg-7',
      conversationId: 'conv-faculty-lounge',
      collegeId: 'Bonsalo College',
      senderId: 'teacher-1',
      senderName: 'Dr. Meera Shah',
      senderRole: 'teacher',
      senderAvatar: 'MS',
      text: 'Noted, Principal ma\'am. Computer Science department internal evaluations will be completed on schedule.',
      status: 'read',
      createdAt: 'Yesterday, 11:30 AM',
    },
    {
      id: 'cmsg-8',
      conversationId: 'conv-college-all',
      collegeId: 'Bonsalo College',
      senderId: 'admin-1',
      senderName: 'Priya Nair',
      senderRole: 'admin',
      senderAvatar: 'PN',
      text: 'Welcome students and staff to the EduPulse Campus Community! You can ask general questions and receive important announcements here.',
      status: 'read',
      createdAt: 'Yesterday, 09:00 AM',
    },
    {
      id: 'cmsg-9',
      conversationId: 'conv-college-all',
      collegeId: 'Bonsalo College',
      senderId: 'student-1',
      senderName: 'Aarav Sharma',
      senderRole: 'student',
      senderAvatar: 'AS',
      text: 'Thank you Principal ma\'am! Excited for the upcoming campus hackathon.',
      status: 'read',
      createdAt: 'Yesterday, 09:25 AM',
    },
  ],
  notifications: [
    { id: 'notif-1', title: 'New material available', description: 'Binary Search Notes was added to Data Structures.', date: '10 min ago', read: false },
    { id: 'notif-2', title: 'Assignment due soon', description: 'Binary Search Tree is due in 9 days.', date: '2 hr ago', read: false },
    { id: 'notif-3', title: 'Class cancelled', description: 'Web Development lab is cancelled today.', date: 'Today', read: true },
  ],
  verifications: [
    { id: 'vr-1', name: 'Arjun Kapoor', employeeId: 'EMP-1044', department: 'Computer Science', appliedDate: '01 Sep 2026', status: 'Pending' },
    { id: 'vr-2', name: 'Neha Kulkarni', employeeId: 'EMP-1045', department: 'Mathematics', appliedDate: '31 Aug 2026', status: 'Pending' },
    { id: 'vr-3', name: 'Sanjay Rao', employeeId: 'EMP-1042', department: 'Information Technology', appliedDate: '29 Aug 2026', status: 'Approved' },
  ],
}