import type { AppearanceConfig } from './appearanceConfig'

export interface ThemePreset {
  id: string
  name: string
  subtitle: string
  description: string
  swatch: {
    primary: string
    secondary: string
    accent: string
    surface: string
  }
  config: Partial<AppearanceConfig>
}

export const themePresets: ThemePreset[] = [
  {
    id: 'ocean-blue',
    name: 'Ocean Glass',
    subtitle: 'Classic Academic Blue & Electric Cyan',
    description: 'Deep navy glass surfaces paired with electric blue and luminous cyan glass orbs.',
    swatch: {
      primary: '#4f8cff',
      secondary: '#765cff',
      accent: '#49d8ff',
      surface: '#101827',
    },
    config: {
      presetId: 'ocean-blue',
      mode: 'dark',
      palette: {
        primary: '#4f8cff',
        primaryGlow: 'rgba(79, 140, 255, 0.35)',
        secondary: '#765cff',
        accent: '#49d8ff',
        background: '#080e1e',
        surface: '#101827',
        surfaceMuted: '#172344',
        card: 'rgba(16, 24, 39, 0.74)',
        glass: 'rgba(16, 24, 39, 0.74)',
        border: 'rgba(255, 255, 255, 0.11)',
        text: '#f8fafc',
        textSecondary: '#94a3b8',
        icon: '#cbd5e1',
        button: '#4f8cff',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#49d8ff',
        hover: 'rgba(255, 255, 255, 0.06)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#4f8cff',
        orbCyan: '#49d8ff',
        orbPurple: '#765cff',
      },
      glass: {
        opacity: 0.74,
        blur: 20,
        brightness: 1.0,
        borderOpacity: 0.11,
        borderWidth: 1,
        shadowIntensity: 0.45,
        saturation: 190,
      },
      orb: {
        shape: 'pill',
        size: 40,
        opacity: 0.95,
        blur: 12,
        glowIntensity: 0.85,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Study',
    subtitle: 'Deep Amethyst & Violet Glow',
    description: 'Regal purple tones with velvet violet glass, glowing amethyst orbs, and soft atmospheric lighting.',
    swatch: {
      primary: '#9061f9',
      secondary: '#c084fc',
      accent: '#e879f9',
      surface: '#171026',
    },
    config: {
      presetId: 'royal-purple',
      mode: 'dark',
      palette: {
        primary: '#9061f9',
        primaryGlow: 'rgba(144, 97, 249, 0.40)',
        secondary: '#c084fc',
        accent: '#e879f9',
        background: '#0d0718',
        surface: '#171026',
        surfaceMuted: '#24173d',
        card: 'rgba(23, 16, 38, 0.76)',
        glass: 'rgba(23, 16, 38, 0.76)',
        border: 'rgba(232, 121, 249, 0.16)',
        text: '#faf5ff',
        textSecondary: '#a8a29e',
        icon: '#d8b4fe',
        button: '#9061f9',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#e879f9',
        hover: 'rgba(144, 97, 249, 0.12)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#9061f9',
        orbCyan: '#e879f9',
        orbPurple: '#c084fc',
      },
      glass: {
        opacity: 0.76,
        blur: 22,
        brightness: 1.02,
        borderOpacity: 0.16,
        borderWidth: 1,
        shadowIntensity: 0.5,
        saturation: 195,
      },
      orb: {
        shape: 'pill',
        size: 42,
        opacity: 0.95,
        blur: 14,
        glowIntensity: 0.9,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'emerald-green',
    name: 'Emerald Campus',
    subtitle: 'Lush Botanical Teal & Mint Glass',
    description: 'Refreshing organic emerald and mint crystal surfaces for focused and calm study sessions.',
    swatch: {
      primary: '#10b981',
      secondary: '#06b6d4',
      accent: '#34d399',
      surface: '#0d1f19',
    },
    config: {
      presetId: 'emerald-green',
      mode: 'dark',
      palette: {
        primary: '#10b981',
        primaryGlow: 'rgba(16, 185, 129, 0.40)',
        secondary: '#06b6d4',
        accent: '#34d399',
        background: '#06130f',
        surface: '#0d1f19',
        surfaceMuted: '#133128',
        card: 'rgba(13, 31, 25, 0.76)',
        glass: 'rgba(13, 31, 25, 0.76)',
        border: 'rgba(52, 211, 153, 0.16)',
        text: '#f0fdf4',
        textSecondary: '#94a3b8',
        icon: '#a7f3d0',
        button: '#10b981',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#34d399',
        hover: 'rgba(16, 185, 129, 0.12)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#10b981',
        orbCyan: '#34d399',
        orbPurple: '#06b6d4',
      },
      glass: {
        opacity: 0.75,
        blur: 20,
        brightness: 1.0,
        borderOpacity: 0.15,
        borderWidth: 1,
        shadowIntensity: 0.45,
        saturation: 190,
      },
      orb: {
        shape: 'pill',
        size: 40,
        opacity: 0.95,
        blur: 12,
        glowIntensity: 0.85,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Campus',
    subtitle: 'Golden Amber & Radiant Coral',
    description: 'Warm dusk aesthetic with rich amber glass, glowing solar coral orbs, and energizing contrast.',
    swatch: {
      primary: '#f97316',
      secondary: '#fb7185',
      accent: '#facc15',
      surface: '#221410',
    },
    config: {
      presetId: 'sunset-orange',
      mode: 'dark',
      palette: {
        primary: '#f97316',
        primaryGlow: 'rgba(249, 115, 22, 0.42)',
        secondary: '#fb7185',
        accent: '#facc15',
        background: '#120a07',
        surface: '#221410',
        surfaceMuted: '#351f18',
        card: 'rgba(34, 20, 16, 0.78)',
        glass: 'rgba(34, 20, 16, 0.78)',
        border: 'rgba(250, 204, 21, 0.16)',
        text: '#fff7ed',
        textSecondary: '#a8a29e',
        icon: '#fed7aa',
        button: '#f97316',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#facc15',
        hover: 'rgba(249, 115, 22, 0.12)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#f97316',
        orbCyan: '#facc15',
        orbPurple: '#fb7185',
      },
      glass: {
        opacity: 0.76,
        blur: 22,
        brightness: 1.02,
        borderOpacity: 0.16,
        borderWidth: 1,
        shadowIntensity: 0.48,
        saturation: 200,
      },
      orb: {
        shape: 'pill',
        size: 42,
        opacity: 0.95,
        blur: 14,
        glowIntensity: 0.9,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'rose-pink',
    name: 'Rose Pink',
    subtitle: 'Vibrant Magenta & Blush Quartz',
    description: 'Elegant cherry blossom and rose quartz glass surfaces with luminous blush indicators.',
    swatch: {
      primary: '#ec4899',
      secondary: '#f43f5e',
      accent: '#f472b6',
      surface: '#24111d',
    },
    config: {
      presetId: 'rose-pink',
      mode: 'dark',
      palette: {
        primary: '#ec4899',
        primaryGlow: 'rgba(236, 72, 153, 0.40)',
        secondary: '#f43f5e',
        accent: '#f472b6',
        background: '#140810',
        surface: '#24111d',
        surfaceMuted: '#381a2e',
        card: 'rgba(36, 17, 29, 0.76)',
        glass: 'rgba(36, 17, 29, 0.76)',
        border: 'rgba(244, 114, 182, 0.16)',
        text: '#fdf2f8',
        textSecondary: '#a8a29e',
        icon: '#fbcfe8',
        button: '#ec4899',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#f472b6',
        hover: 'rgba(236, 72, 153, 0.12)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#ec4899',
        orbCyan: '#f472b6',
        orbPurple: '#f43f5e',
      },
      glass: {
        opacity: 0.75,
        blur: 20,
        brightness: 1.0,
        borderOpacity: 0.16,
        borderWidth: 1,
        shadowIntensity: 0.46,
        saturation: 190,
      },
      orb: {
        shape: 'pill',
        size: 40,
        opacity: 0.95,
        blur: 12,
        glowIntensity: 0.85,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'cyber-cyan',
    name: 'Cyber Cyan',
    subtitle: 'Neon Azure & Obsidian Matrix',
    description: 'Ultra-high-tech neon cyan lights with pure obsidian acrylic glass and sharp futuristic reflections.',
    swatch: {
      primary: '#06b6d4',
      secondary: '#3b82f6',
      accent: '#22d3ee',
      surface: '#081720',
    },
    config: {
      presetId: 'cyber-cyan',
      mode: 'dark',
      palette: {
        primary: '#06b6d4',
        primaryGlow: 'rgba(6, 182, 212, 0.45)',
        secondary: '#3b82f6',
        accent: '#22d3ee',
        background: '#030a0f',
        surface: '#081720',
        surfaceMuted: '#0f2736',
        card: 'rgba(8, 23, 32, 0.78)',
        glass: 'rgba(8, 23, 32, 0.78)',
        border: 'rgba(34, 211, 238, 0.20)',
        text: '#ecfeff',
        textSecondary: '#94a3b8',
        icon: '#a5f3fc',
        button: '#06b6d4',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#22d3ee',
        hover: 'rgba(6, 182, 212, 0.12)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#06b6d4',
        orbCyan: '#22d3ee',
        orbPurple: '#3b82f6',
      },
      glass: {
        opacity: 0.78,
        blur: 24,
        brightness: 1.05,
        borderOpacity: 0.2,
        borderWidth: 1,
        shadowIntensity: 0.52,
        saturation: 210,
      },
      orb: {
        shape: 'pill',
        size: 42,
        opacity: 0.98,
        blur: 15,
        glowIntensity: 0.95,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    subtitle: 'Stealth Obsidian & Moonlit Frost',
    description: 'Near-black minimalist elegance with moonlight glass reflections and crisp typography.',
    swatch: {
      primary: '#64748b',
      secondary: '#475569',
      accent: '#94a3b8',
      surface: '#0b0f17',
    },
    config: {
      presetId: 'midnight',
      mode: 'dark',
      palette: {
        primary: '#64748b',
        primaryGlow: 'rgba(148, 163, 184, 0.25)',
        secondary: '#475569',
        accent: '#cbd5e1',
        background: '#04060a',
        surface: '#0b0f17',
        surfaceMuted: '#141b29',
        card: 'rgba(11, 15, 23, 0.82)',
        glass: 'rgba(11, 15, 23, 0.82)',
        border: 'rgba(255, 255, 255, 0.08)',
        text: '#f8fafc',
        textSecondary: '#64748b',
        icon: '#94a3b8',
        button: '#334155',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#cbd5e1',
        hover: 'rgba(255, 255, 255, 0.04)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#475569',
        orbCyan: '#cbd5e1',
        orbPurple: '#334155',
      },
      glass: {
        opacity: 0.82,
        blur: 16,
        brightness: 0.95,
        borderOpacity: 0.08,
        borderWidth: 1,
        shadowIntensity: 0.35,
        saturation: 140,
      },
      orb: {
        shape: 'pill',
        size: 38,
        opacity: 0.85,
        blur: 8,
        glowIntensity: 0.5,
        borderWidth: 1,
        gradientStyle: 'linear',
        animation: true,
      },
    },
  },
  {
    id: 'monochrome',
    name: 'Minimal Study',
    subtitle: 'Monochrome High-Contrast Slate',
    description: 'Clean architectural black, white, and silver with minimal blur and focused clarity.',
    swatch: {
      primary: '#ffffff',
      secondary: '#e2e8f0',
      accent: '#ffffff',
      surface: '#121417',
    },
    config: {
      presetId: 'monochrome',
      mode: 'dark',
      palette: {
        primary: '#e2e8f0',
        primaryGlow: 'rgba(255, 255, 255, 0.20)',
        secondary: '#cbd5e1',
        accent: '#ffffff',
        background: '#090a0c',
        surface: '#121417',
        surfaceMuted: '#1c1f24',
        card: 'rgba(18, 20, 23, 0.85)',
        glass: 'rgba(18, 20, 23, 0.85)',
        border: 'rgba(255, 255, 255, 0.12)',
        text: '#ffffff',
        textSecondary: '#94a3b8',
        icon: '#cbd5e1',
        button: '#272a30',
        buttonText: '#ffffff',
        activeNav: '#ffffff',
        activeOrb: '#ffffff',
        hover: 'rgba(255, 255, 255, 0.06)',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        orbBlue: '#64748b',
        orbCyan: '#ffffff',
        orbPurple: '#475569',
      },
      glass: {
        opacity: 0.85,
        blur: 10,
        brightness: 1.0,
        borderOpacity: 0.12,
        borderWidth: 1,
        shadowIntensity: 0.2,
        saturation: 100,
      },
      orb: {
        shape: 'pill',
        size: 38,
        opacity: 0.9,
        blur: 6,
        glowIntensity: 0.4,
        borderWidth: 1,
        gradientStyle: 'none',
        animation: false,
      },
    },
  },
]
